import logging
import math
from utils.functions.database_functions import get_db_connection, close_db_connection
# Combat
#_______________________________________________________________________________________________________________________
