import logging
import math
from utils.functions.database_functions import get_db_connection, close_db_connection
from utils.functions.character_functions import active_character

# mobs
#_______________________________________________________________________________________________________________________
